server:
  port: 8002

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          resource:
            provider: resource
            client-id: ishare
            client-secret: oauth2
#            access-token-uri: http://authorizer-service.dev.yffjglcms.com:8080/oauth/token
            # code 回调地址
            redirectUri: "{baseUrl}/oauth2/code/{registrationId}"
            scope:
              - READ
              - WRITE
            authorizationGrantType: authorization_code
        #          qq:
        #            provider: resource
        #            client-id: ishare
        #            client-secret: oauth2
        #            access-token-uri: http://authorizer-service.dev.yffjglcms.com:8080/oauth/token
        #            # code 回调地址
        #            redirectUri: "{baseUrl}/oauth2/code/{registrationId}"
        #            scope:
        #              - READ
        #              - WRITE
        #            authorizationGrantType: authorization_code
        provider:
          resource:
            # 用于 授予 client 权限的地址，会拼接 当前网址地址
            authorizationUri: http://authorizer-service.dev.yffjglcms.com:8080/oauth/authorize
            # 获取access_token
            tokenUri: http://authorizer-service.dev.yffjglcms.com:8080/oauth/token
            # 获取access_token后，并获取 userInfo
            userInfoUri:  http://resource-service.dev.yffjglcms.com:8081/api/v1/user
            userNameAttribute: username

logging:
  level:
    org.springframework.security: debug