server:
  port: 8002

spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    "com.yffjglcms": debug

sso:
  key:
    pub:
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgVUTh5VYsmaEvtD+PZgk/07EcxNhkfMgn1eoiGqB9snoZtTMKJtDq0mpf7gMB/0UYlMR8aQZ1rmyfnlC7kRhtSzMmrZ4WfPicoQsNKlciK/1aG+S4KLynLgoSLOwbyi1MrFBNkQT/HJiwGxdC9YF82FFHVbVhyl+ccIHXgY9NFEp+tBokU6RMVRBGgNszriw/RvHPnwEvG7KmSYUIkCpU8r1WcGawQ0Xabt7qtwfaTYYC5Nxl7pbqJSsqMpg9dfXoaqP0tnGxPj2ArMFK9TBUXStLSLEqHzpu//3Plu2BBq2PFoR1EIj01DV2dCFt0FBOk/TXctJXewRxgKO4eK6XQIDAQAB
      -----END PUBLIC KEY-----